import React from 'react';
import type {GetStaticPropsContext, InferGetStaticPropsType} from 'next';
import Head from 'next/head';

import Layout from '@com/Layout';
import {getConfig, markdownToHtml, getPostBySlug, getAllPosts} from '@libs';

export default function Tags({config, tag}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <Layout config={config}>
      <Head>
        <title>tag:{tag}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      태그 페이지
    </Layout>
  );
}

export async function getStaticProps({params}: GetStaticPropsContext<{tag: string}>) {
  const config = await getConfig();
  const slug = params!.tag;

  const post = getPostBySlug(slug, ['title', 'date', 'slug', 'tags', 'content', 'img']);
  const content = await markdownToHtml(post!.content || '', '');

  return {
    props: {
      config: {...config},
      tag: params!.tag,
      post: {
        ...post,
      },

      content,
    },
  };
}

export async function getStaticPaths() {
  const posts = getAllPosts(['slug']);
  const paths = posts.map(post => ({
    params: {
      tag: post.slug,
    },
  }));

  return {
    paths: [],
    fallback: false,
  };
}
