import React from 'react';
import type {GetStaticPropsContext, InferGetStaticPropsType} from 'next';
import Head from 'next/head';

import Layout from '@com/Layout';
import {getConfig, markdownToHtml, getPostBySlug, getAllPosts} from '@libs';
import {getAllTags, getPostsByTag} from 'src/libs/api';
import Link from 'next/link';

export default function Tags({config, tag, posts}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <Layout config={config}>
      <Head>
        <title>tag:{tag}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>
        <h2> 태그 페이지</h2>
        <ul>
          {posts.map(({slug, date, title}) => (
            <li key={slug} style={{marginBottom: '20px'}}>
              <Link href={`/p/${slug}`}>
                <a>
                  {title}
                  <br />
                  {date}
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </section>
    </Layout>
  );
}

export async function getStaticProps({params}: GetStaticPropsContext<{tag: string}>) {
  const config = await getConfig();
  const posts = getPostsByTag(params!.tag, ['slug', 'title', 'description', 'date', 'img']);
  console.debug(posts);

  return {
    props: {
      config: {...config},
      tag: params!.tag,
      posts,
    },
  };
}

export async function getStaticPaths() {
  const tags = getAllTags();
  console.log(tags);
  const paths = tags.map(tag => ({
    params: {
      tag: tag,
    },
  }));

  return {
    paths: paths,
    fallback: false,
  };
}
