import React from 'react';
import type {GetStaticPropsContext, InferGetStaticPropsType} from 'next';
import Head from 'next/head';

import Layout from '@com/Layout';
import {getPostBySlug} from 'src/libs/api';
import {getConfig, markdownToHtml} from '@libs';

function Home({config}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <Layout config={config}>
      <Head>
        <title>{config.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </Layout>
  );
}

export async function getStaticProps({params}: GetStaticPropsContext<{tag: string}>) {
  const config = await getConfig();
  const slug = params!.tag;

  const post = getPostBySlug(slug, ['title', 'date', 'slug', 'tags', 'content', 'img']);
  const content = await markdownToHtml(post!.content || '');

  return {
    props: {
      config: {...config},
      post: {
        ...post,
      },

      content,
    },
  };
}
